---
# Run basic tests for this app on the latest aiidalab-docker image.
name: continuous-integration
on: [push, pull_request]

jobs:
    test-package:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package and its dependencies
              run: |
                  pip install .[dev]

            - name: Run pytest
              run: pytest tests -v --cov
