---
# Run basic tests for this app on the latest aiidalab-docker image.
name: continuous-integration
on: [push, pull_request]

jobs:
    test-package:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package and its dependencies
              run: |
                  pip install .[dev,opencl]
                  sudo apt install pocl-opencl-icd

            - name: Run pytest
              run: pytest tests -v --cov

            - name: Save test images
              uses: actions/upload-artifact@v3
              with:
                  name: test-images
                  path: ./*.png

    test-docker:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Build a Docker image
              run: docker build -t ppafm:latest .

            - name: Execute the container.
              run: |
                  cd examples/PTCDA_single/
                  docker run --rm -it -v ${PWD}:/exec ppafm:latest ppafm-generate-ljff -i PTCDA.xyz
                  docker run --rm -it -v ${PWD}:/exec ppafm:latest ppafm-generate-elff-point-charges -i PTCDA.xyz --tip s
                  docker run --rm -it -v ${PWD}:/exec ppafm:latest ppafm-relaxed-scan -k 0.5 -q -0.10
                  docker run --rm -it -v ${PWD}:/exec ppafm:latest ppafm-plot-results -k 0.5 -q -0.10 --arange 0.5 2.0 2 --df
