---
name: Publish on PyPI

on:
    push:
        tags:
        # Tags that start with the "v" prefix are published on PyPI.
            - v*
        # !!!!!!!!!!!!!
        # TODO: remove this before merging to main.
        branches:
            - update/automate-release
        # !!!!!!!!!!!!!

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install build
              run: python -m pip install --upgrade build

            - name: Build a binary wheel and a source tarball
              run: python -m build --sdist --wheel --outdir dist/

            - name: Upload distribution artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: release
                  path: dist/
